### PR TITLE
Fixed a Bug

### PR DESCRIPTION
**Pull request by Godsoft029**
Fixed a bug where you couldnt destroy any blocks.

### CODE REVIEW

**Comment by gaoyichuan** [comment]
Players in advanture mode should not break any blocks

**Comment by Godsoft029** [comment]
https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/Player.java#L1594

**Comment by SupremeMortal** [comment]
@gaoyichuan This is a bug. You have it around the wrong way. Please reopen and commit

**Comment by SupremeMortal** [comment]
You have set it so players who are not in adventure cannot break blocks

**Comment by Godsoft029** [comment]
Yep

**Comment by SupremeMortal** [comment]
Added it to my pull request here #22

**Pull request closed without merging**
